- project:
    templates:
      - openstack-python-jobs-neutron
      - check-requirements
      - publish-openstack-sphinx-docs
    check:
      jobs:
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/networking-sfc
              - openstack/neutron-dynamic-routing
        - openstack-tox-pep8:
            required-projects:
              - openstack/networking-sfc
              - openstack/neutron-dynamic-routing
        - openstack-tox-py27:
            required-projects:
              - openstack/neutron
              - openstack/networking-sfc
              - openstack/neutron-dynamic-routing
        - openstack-tox-py35:
            voting: false
            required-projects:
              - openstack/neutron
              - openstack/networking-sfc
              - openstack/neutron-dynamic-routing
    gate:
      jobs:
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/networking-sfc
              - openstack/neutron-dynamic-routing
        - openstack-tox-pep8:
            required-projects:
              - openstack/networking-sfc
              - openstack/neutron-dynamic-routing
        - openstack-tox-py27:
            required-projects:
              - openstack/neutron
              - openstack/networking-sfc
              - openstack/neutron-dynamic-routing
    post:
      jobs:
        - publish-openstack-python-branch-tarball:
            required-projects:
              - openstack/networking-sfc
              - openstack/neutron-dynamic-routing

