- project:
    name: openstack/dragonflow
    check:
      jobs:
        - tempest-dsvm-dragonflow:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - dragonflow-dsvm-rally:
            voting: false
        - dragonflow-dsvm-fullstack-redis
        - dragonflow-dsvm-fullstack-etcd-zmq:
            voting: false
        - legacy-install-dsvm-dragonflow-kuryr-kubernetes:
            voting: false
        - legacy-openstack-ansible-os_neutron-ansible-dragonflow:
            voting: false
            branches: ^(?!stable/newton).*$
    gate:
      jobs:
        - dragonflow-dsvm-fullstack-redis

- job:
    name: dragonflow-dsvm-fullstack-redis
    parent: legacy-dsvm-base
    run: zuul/dragonflow-dsvm-fullstack-redis/run
    post-run: zuul/dragonflow-dsvm-fullstack-redis/post
    timeout: 9900
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/dragonflow
      - openstack/neutron
      - openstack/networking-sfc
      - openstack/neutron-dynamic-routing

- job:
    name: dragonflow-dsvm-fullstack-etcd-zmq
    parent: legacy-dsvm-base
    run: zuul/dragonflow-dsvm-fullstack-etcd-zmq/run
    post-run: zuul/dragonflow-dsvm-fullstack-etcd-zmq/post
    timeout: 9900
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/dragonflow
      - openstack/neutron
      - openstack/networking-sfc
      - openstack/neutron-dynamic-routing

- job:
    name: dragonflow-dsvm-rally
    parent: legacy-dsvm-base
    run: zuul/dragonflow-dsvm-rally/run
    post-run: zuul/dragonflow-dsvm-rally/post
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/dragonflow
      - openstack/neutron
      - openstack/networking-sfc
      - openstack/neutron-dynamic-routing
      - openstack/rally

- job:
    name: tempest-dsvm-dragonflow
    parent: legacy-dsvm-base
    run: zuul/tempest-dsvm-dragonflow/run
    post-run: zuul/tempest-dsvm-dragonflow/post
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/dragonflow
      - openstack/neutron
      - openstack/networking-sfc
      - openstack/neutron-dynamic-routing
      - openstack/tempest
