- project:
    name: openstack/dragonflow
    check:
      jobs:
        - tempest-dsvm-dragonflow:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - dragonflow-dsvm-rally:
            voting: false
        - dragonflow-dsvm-fullstack
        - dragonflow-dsvm-fullstack-zmq:
            voting: false
        - legacy-install-dsvm-dragonflow-kuryr-kubernetes:
            voting: false
        - openstack-ansible-dragonflow-ubuntu-xenial-nv:
            voting: false
    gate:
      jobs:
        - dragonflow-dsvm-fullstack

- job:
    name: dragonflow-dsvm-fullstack
    parent: legacy-dsvm-base
    run: zuul/dragonflow-dsvm-fullstack/run
    post-run: zuul/dragonflow-dsvm-fullstack/post
    timeout: 9900
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/dragonflow
      - openstack/neutron
      - openstack/networking-sfc
      - openstack/neutron-dynamic-routing

- job:
    name: dragonflow-dsvm-fullstack-zmq
    parent: legacy-dsvm-base
    run: zuul/dragonflow-dsvm-fullstack-zmq/run
    post-run: zuul/dragonflow-dsvm-fullstack-zmq/post
    timeout: 9900
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/dragonflow
      - openstack/neutron
      - openstack/networking-sfc
      - openstack/neutron-dynamic-routing

- job:
    name: dragonflow-dsvm-rally
    parent: legacy-dsvm-base
    run: zuul/dragonflow-dsvm-rally/run
    post-run: zuul/dragonflow-dsvm-rally/post
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/dragonflow
      - openstack/neutron
      - openstack/networking-sfc
      - openstack/neutron-dynamic-routing
      - openstack/rally

- job:
    name: tempest-dsvm-dragonflow
    parent: legacy-dsvm-base
    run: zuul/tempest-dsvm-dragonflow/run
    post-run: zuul/tempest-dsvm-dragonflow/post
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/dragonflow
      - openstack/neutron
      - openstack/networking-sfc
      - openstack/neutron-dynamic-routing
      - openstack/tempest
