- project:
    check:
      jobs:
        - dragonflow-tempest:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - dragonflow-dsvm-rally:
            voting: false
        - dragonflow-dsvm-fullstack-redis
        - dragonflow-dsvm-fullstack-etcd-zmq
        - dragonflow-openstack-ansible-cross-repo:
            voting: false
        - kuryr-kubernetes-tempest-dragonflow:
            voting: false
    gate:
      jobs:
        - dragonflow-dsvm-fullstack-redis

- job:
    name: dragonflow-dsvm-fullstack-redis
    parent: legacy-dsvm-base
    run: zuul/dragonflow-dsvm-fullstack-redis/run.yaml
    post-run: zuul/dragonflow-dsvm-fullstack-redis/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/dragonflow
      - openstack/neutron
      - openstack/networking-sfc
      - openstack/neutron-dynamic-routing

- job:
    name: dragonflow-dsvm-fullstack-etcd-zmq
    parent: legacy-dsvm-base
    run: zuul/dragonflow-dsvm-fullstack-etcd-zmq/run.yaml
    post-run: zuul/dragonflow-dsvm-fullstack-etcd-zmq/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/dragonflow
      - openstack/neutron
      - openstack/networking-sfc
      - openstack/neutron-dynamic-routing

- job:
    name: dragonflow-dsvm-rally
    parent: legacy-dsvm-base
    run: zuul/dragonflow-dsvm-rally/run.yaml
    post-run: zuul/dragonflow-dsvm-rally/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/dragonflow
      - openstack/neutron
      - openstack/networking-sfc
      - openstack/neutron-dynamic-routing
      - openstack/rally

- job:
    name: dragonflow-tempest
    parent: legacy-dsvm-base
    run: zuul/tempest-dsvm-dragonflow/run.yaml
    post-run: zuul/tempest-dsvm-dragonflow/post.yaml
    timeout: 10800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/dragonflow
      - openstack/neutron
      - openstack/networking-sfc
      - openstack/neutron-dynamic-routing
      - openstack/tempest
      - openstack/neutron-tempest-plugin

- job:
    name: dragonflow-openstack-ansible-cross-repo
    parent: openstack-ansible-cross-repo-functional
    required-projects:
      - openstack/requirements
      - openstack/openstack-ansible-os_neutron
    vars:
      tox_env: dragonflow
      osa_test_repo: openstack/openstack-ansible-os_neutron
