#!/bin/bash
#
#
# ``plugin.sh`` calls the following methods in the sourced driver:
#
# - nb_db_driver_install_server
# - nb_db_driver_install_client
# - nb_db_driver_start_server
# - nb_db_driver_stop_server
# - nb_db_driver_clean

RAMCLOUD=$DEST/ramcloud
RAMCLOUD_LIB=$RAMCLOUD/lib
RAMCLOUD_BIN=$RAMCLOUD/bin
RAMCLOUD_MASTER_IP=${RAMCLOUD_MASTER_IP:-'127.0.0.1'}
RAMCLOUD_COORDINATOR_IP=${RAMCLOUD_COORDINATOR_IP:-'127.0.0.1'}
RAMCLOUD_MASTER_PORT=${RAMCLOUD_MASTER_PORT:-'21221'}
RAMCLOUD_COORDINATOR_PORT=${RAMCLOUD_COORDINATOR_PORT:-'21222'}
RAMCLOUD_TRANSPORT=${RAMCLOUD_TRANSPORT:-'fast+udp'}
RAMCLOUD_TABLE_NAMES=${RAMCLOUD_TABLE_NAMES:-'secgroup','dragonflow','chassis','lswitch','lport','lrouter','tunnel_key'}


export PYTHONPATH=$PYTHONPATH:$DEST/dragonflow/
NB_DRIVER_CLASS="ramcloud_db_driver.RamCloudDbDriver"

function nb_db_driver_install_server {
    echo "Installing RAMCloud server"
    git_clone https://github.com/dsivov/RamCloudBin.git $RAMCLOUD
    echo export LD_LIBRARY_PATH="$RAMCLOUD_LIB":"$LD_LIBRARY_PATH" | tee -a $HOME/.bashrc
}

function nb_db_driver_install_client {
    echo "Installing RAMCloud client"
    git_clone https://github.com/dsivov/RamCloudBin.git $RAMCLOUD
}

function nb_db_driver_start_server {
    if is_service_enabled df-rccoordinator ; then
        sudo killall coordinator
        $RAMCLOUD_BIN/coordinator -C ${RAMCLOUD_TRANSPORT}:host=${RAMCLOUD_COORDINATOR_IP},port=${RAMCLOUD_COORDINATOR_PORT} &
    fi

    if is_service_enabled df-rcmaster ; then
        sudo killall server
        $RAMCLOUD_BIN/server ${RAMCLOUD_TRANSPORT}:host=${RAMCLOUD_MASTER_IP},port=${RAMCLOUD_MASTER_PORT} -C ${RAMCLOUD_TRANSPORT}:host=${RAMCLOUD_COORDINATOR_IP},port=${RAMCLOUD_COORDINATOR_PORT} &
    fi

    # Create the tables in the DB
    PYTHONPATH=$PYTHONPATH:$DEST/dragonflow/
    python $DEST/dragonflow/dragonflow/db/drivers/table_setup.py -d ramcloud -t ${RAMCLOUD_TABLE_NAMES} -i ${RAMCLOUD_COORDINATOR_IP} -p ${RAMCLOUD_COORDINATOR_PORT}
}

function nb_db_driver_stop_server {
    if is_service_enabled df-rccoordinator ; then
        sudo killall coordinator
    fi
     if is_service_enabled df-rcmaster ; then
        sudo killall server
    fi
}