#!/bin/bash
#
#
# ``plugin.sh`` calls the following methods in the sourced driver:
#
# - nb_db_driver_install_server
# - nb_db_driver_install_client
# - nb_db_driver_start_server
# - nb_db_driver_stop_server
# - nb_db_driver_clean
NB_DRIVER_CLASS="dragonflow.db.drivers.rethink_db_driver.RethinkDbDriver"
RETHINKDB_IP=${RETHINKDB_IP:-"$HOST_IP"}
RETHINKDB_PORT=${RETHINKDB_PORT:-'28015'}
RETHINKDB_TABLE_NAMES=${RETHINKDB_TABLE_NAMES:-'secgroup','dragonflow','chassis','lswitch','lport','lrouter','tunnel_key'}

function nb_db_driver_install_server {
    if is_service_enabled df-rethinkdb-server ; then
       echo "Installing RethinkDB Server"
       if is_ubuntu; then
          source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
          wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install rethinkdb
          echo "Installing RethinkDB client"
          sudo pip install rethinkdb
          echo "starting rethinkdb"
          rethinkdb --bind all --daemon --driver-port ${RETHINKDB_PORT}
          until pids=$(pidof rethinkdb)
          do         sleep 1;        echo "sleep 1, waiting for rethinkdb to start";        done
          echo "sleep 5, waiting for rethinkdb to start"
          sleep 5
          echo "Deleting all tables from RethinkDB"
          python $DEST/dragonflow/dragonflow/db/drivers/table_setup_rethinkdb.py -i ${RETHINKDB_IP} -p ${RETHINKDB_PORT} -r
          sudo killall rethinkdb
       else
          die $LINENO "Warning - RethinkDB is currently supported only for Ubuntu. Any other distros are currently not supported."
       fi
    fi
}

function nb_db_driver_install_client {
    echo "Installing RethinkDB client"
    sudo pip install rethinkdb
    echo "Finished installing RethinkDB"
}

function nb_db_driver_start_server {
    if is_service_enabled df-rethinkdb-server ; then
       echo "starting rethinkdb"
       rethinkdb --bind all --daemon --driver-port ${RETHINKDB_PORT}
       until pids=$(pidof rethinkdb)
       do         sleep 1;        echo "sleep 1, waiting for rethinkdb to start";        done
       echo "sleep 5, waiting for rethinkdb to start"
       sleep 5
       echo "RethinkDB tables setup"
       python $DEST/dragonflow/dragonflow/db/drivers/table_setup_rethinkdb.py -t ${RETHINKDB_TABLE_NAMES} -i ${RETHINKDB_IP} -p ${RETHINKDB_PORT}
    fi
}

function nb_db_driver_stop_server {
    if is_service_enabled df-rethinkdb-server ; then
        sudo killall rethinkdb
    fi
}

function nb_db_driver_status_server
{
   TEMP_PIDS=`ps cax | grep rethinkdb`
   if [ -z "$TEMP_PIDS" ]; then
     return 1
   fi
   return 0
}

