#!/bin/bash
#
#
# ``plugin.sh`` calls the following methods in the sourced driver:
#
# - nb_db_driver_install_server
# - nb_db_driver_install_client
# - nb_db_driver_start_server
# - nb_db_driver_stop_server
# - nb_db_driver_clean
# - nb_db_driver_configure

HOSTNAME=`hostname -f`

if is_ubuntu ; then
    UBUNTU_RELEASE_BASE_NUM=`lsb_release -r | awk '{print $2}' | cut -d '.' -f 1`
fi

function _zookeeper_env {
    export ZOOKEEPER_DATA_DIR="/var/lib/zookeeper"
    export ZOOKEEPER_LOG_DIR="/var/log/zookeeper"
    export ZOOKEEPER_DIR="/etc/zookeeper"
}

function nb_db_driver_install_server {
    if is_service_enabled df-zookeeper-server ; then
        _zookeeper_env
        echo "Installing Zookeeper server"
        ZOOKEEPER_CONF_DIR="${ZOOKEEPER_DIR}"
        ZOOKEEPER_CONF_FILE="${ZOOKEEPER_CONF_DIR}/zoo.cfg"
        ZOOKEEPER_CONF_SAMPLE_FILE="${ZOOKEEPER_CONF_DIR}/zoo_sample.cfg"
        sudo mkdir -p $ZOOKEEPER_DATA_DIR
        sudo mkdir -p $ZOOKEEPER_LOG_DIR
        sudo mkdir -p $ZOOKEEPER_CONF_DIR
        if is_ubuntu; then
            install_package zookeeperd
        elif is_fedora; then
            install_package zookeeper
        else
            die $LINENO "Other distributions are not supported"
        fi
        sudo cp $ZOOKEEPER_CONF_SAMPLE_FILE $ZOOKEEPER_CONF_FILE

        echo "Configuring Zookeeper"
        if [ -f $ZOOKEEPER_CONF_FILE ] ; then
            sudo sed -i "/^dataDir=/c dataDir=${ZOOKEEPER_DATA_DIR}" $ZOOKEEPER_CONF_FILE
            sudo sed -i "/^dataLogDir=/c dataLogDir=${ZOOKEEPER_LOG_DIR}" $ZOOKEEPER_CONF_FILE
            sudo sed -i "/^clientPort=/c clientPort=${REMOTE_DB_PORT}" $ZOOKEEPER_CONF_FILE
            local result=`grep "server.1" $ZOOKEEPER_CONF_FILE`
            if [ $result -eq 0 ]; then
                sudo sed -i "/^[#server.1=|server.1=]/c server.1=${HOSTNAME}:2888:3888" $ZOOKEEPER_CONF_FILE
            else
                echo "server.1=${HOSTNAME}:2888:3888" | sudo tee -a $ZOOKEEPER_CONF_FILE
            fi
        fi
        echo "1" | sudo tee $ZOOKEEPER_CONF_DIR/myid
    fi
}

function nb_db_driver_clean {
    if is_ubuntu; then
        uninstall_package -y zookeeperd
    elif is_fedora; then
        uninstall_package -y zookeeper
    fi
    if [ -f "/etc/systemd/system/zookeeper.service" ] ; then
        sudo rm /etc/systemd/system/zookeeper.service
        sudo systemctl daemon-reload
    fi
}

function nb_db_driver_install_client {
    echo 'Zookeeper client sdk is in the requirements file.'
}

function nb_db_driver_start_server {
    if is_service_enabled df-zookeeper-server ; then
        _zookeeper_env
        start_service zookeeper
    fi
}

function nb_db_driver_stop_server {
    if is_service_enabled df-zookeeper-server ; then
        _zookeeper_env
        stop_service zookeeper
    fi
}

function nb_db_driver_configure {
    :
}
