- hosts: all
  name: Autoconverted job legacy-dragonflow-dsvm-fullstack from old job gate-dragonflow-dsvm-fullstack-ubuntu-xenial
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          enable_plugin dragonflow git://git.openstack.org/openstack/dragonflow
          Q_ENABLE_DRAGONFLOW_LOCAL_CONTROLLER=True
          # Add bgp project to fullstack gate job.
          enable_plugin neutron-dynamic-routing git://git.openstack.org/openstack/neutron-dynamic-routing
          DR_MODE=df-bgp
          # Add networking-sfc
          enable_plugin networking-sfc git://git.openstack.org/openstack/networking-sfc

          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_INSTALL_TESTONLY=1


          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          export PROJECTS="openstack/dragonflow $PROJECTS"
          export PROJECTS="openstack/neutron-dynamic-routing $PROJECTS"
          export PROJECTS="openstack/networking-sfc $PROJECTS"

          export DEVSTACK_GATE_SETTINGS=/opt/stack/new/dragonflow/devstack/devstackgaterc-fullstack-redis

          function gate_hook {
              bash -xe $BASE/new/dragonflow/dragonflow/tests/contrib/gate_hook.sh fullstack
          }
          export -f gate_hook

          function post_test_hook {
              bash -xe $BASE/new/dragonflow/dragonflow/tests/contrib/post_test_hook.sh fullstack
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
